#!/usr/bin/env python3
"""Keep the ZMK shield in step with the PCBs.

  python3 ergogen/tools/zmk.py           # rewrite the generated blocks in boards/shields/fortemis/
  python3 ergogen/tools/zmk.py --check   # exit 1 if they no longer match pcb/*.kicad_pcb

Reads each half's switches from its routed KiCad PCB (through KiCad's bundled Python, like
case.py): the XIAO pin each switch is wired to, and where the switch sits. From those it fills in
the blocks between the `begin: generated by ergogen/tools/zmk.py` and `end: generated` markers:

  fortemis_left.overlay, fortemis_right.overlay   input-gpios, in keymap order
  fortemis.dtsi                                   the physical layout ZMK Studio draws

Keymap order is rows top, home, bottom, then the thumbs; each row runs left to right as the
keyboard sits on the desk.
"""
import json, pathlib, subprocess, sys, tempfile

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from pcb import KICAD_PY, PCB, ROOT  # noqa: E402

SHIELD = ROOT / 'boards' / 'shields' / 'fortemis'
BEGIN, END = 'begin: generated by ergogen/tools/zmk.py', 'end: generated'
# XIAO nRF52840 Plus pin -> nRF52840 (port, pin), from Seeed's pinout. D16 (P0.31) senses the
# battery voltage and has no key. D14 and D15 are the NFC pins; the half overlays turn NFC off.
GPIO = {'D0': (0, 2), 'D1': (0, 3), 'D2': (0, 28), 'D3': (0, 29), 'D4': (0, 4), 'D5': (0, 5),
        'D6': (1, 11), 'D7': (1, 12), 'D8': (1, 13), 'D9': (1, 14), 'D10': (1, 15),
        'D11': (0, 15), 'D12': (0, 19), 'D13': (1, 1), 'D14': (0, 9), 'D15': (0, 10),
        'D17': (1, 3), 'D18': (1, 5), 'D19': (1, 7)}
UNIT = 18.0                # mm per key unit: the Choc column pitch
CAP = (17.5, 16.5)         # Choc keycap, mm
ROW_PITCH = 17.0
COLUMNS = ['pinky', 'ring', 'middle', 'index', 'inner']
THUMBS = ['tuck', 'near', 'far']
ROWS = ['top', 'home', 'bottom']


def switches(board):
    with tempfile.TemporaryDirectory() as d:
        out = pathlib.Path(d) / 'geom.json'
        r = subprocess.run([KICAD_PY, str(pathlib.Path(__file__).with_name('pcb_kicad.py')), 'geom',
                            str(PCB / f'{board}.kicad_pcb'), str(out)], capture_output=True, text=True)
        if r.returncode:
            sys.exit(r.stdout + r.stderr)
        fps = json.loads(out.read_text())['footprints']
    keys = []
    for f in fps:
        if f['lib'].startswith('switch_'):
            pins = {p['net'] for p in f['pads']} - {'GND', ''}
            assert len(pins) == 1 and pins <= GPIO.keys(), f'{board} {f["ref"]}: nets {pins}'
            # KiCad angles are counterclockwise; a footprint may also be turned 180 degrees to
            # move its hot-swap socket, which doesn't change the key
            keys.append({'pin': pins.pop(), 'xy': np.array([f['x'], f['y']]),
                         'rot': (f['rot'] + 90) % 180 - 90})
    return keys


def keymap_order(keys, right):
    """(key, name) in keymap order for one half."""
    thumbs = sorted([k for k in keys if abs(k['rot']) > 15], key=lambda k: k['xy'][0])
    main = sorted([k for k in keys if abs(k['rot']) <= 15], key=lambda k: k['xy'][0])
    assert len(thumbs) == 3 and len(main) == 15, 'expected 15 main keys and 3 thumbs per half'
    cols = [sorted(main[i:i + 3], key=lambda k: k['xy'][1]) for i in range(0, 15, 3)]
    for c in cols:  # grouping check: a column is three keys at one angle, a row pitch apart
        assert len({k['rot'] for k in c}) == 1
        assert all(abs(np.linalg.norm(a['xy'] - b['xy']) - ROW_PITCH) < 0.05 for a, b in zip(c, c[1:]))
    cnames, tnames = (COLUMNS[::-1], THUMBS[::-1]) if right else (COLUMNS, THUMBS)
    rows = [[(c[r], f'{ROWS[r]} {cnames[i]}') for i, c in enumerate(cols)] for r in range(3)]
    return rows + [[(t, f'{tnames[i]} thumb') for i, t in enumerate(thumbs)]]


def positions():
    """Keymap position -> (key, name, half). Positions interleave the halves row by row."""
    halves = {h: keymap_order(switches(f'fortemis_{h}'), h == 'right') for h in ('left', 'right')}
    return [(k, n, h) for r in range(4) for h in ('left', 'right') for k, n in halves[h][r]]


def gpios(keys, half):
    """input-gpios for one half: its keys in keymap order, each pin pulled up and shorted to GND."""
    mine = [(p, k, n) for p, (k, n, h) in enumerate(keys) if h == half]
    width = max(len(n) for _, _, n in mine)
    lines = ['input-gpios']
    for i, (p, k, n) in enumerate(mine):
        port, pin = GPIO[k['pin']]
        lines.append(f'    {"=" if i == 0 else ","} <&gpio{port} {pin:2d} (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>'
                     f'  // {p:2d} {n:{width}}  {k["pin"]}')
    return lines + ['    ;']


def cu(v):
    v = int(round(v))
    return f'({v})' if v < 0 else str(v)


def layout(keys):
    """ZMK physical layout: centi-units of UNIT mm, y down, rotation clockwise about the key centre."""
    w, h = (np.array(CAP) / UNIT * 100).round()
    corners = np.array([[-1, -1], [1, -1], [1, 1], [-1, 1]]) * np.array(CAP) / 2
    rots = [np.radians(-k['rot']) for k, _, _ in keys]   # KiCad (y down) ccw -> ZMK clockwise
    pts = [k['xy'] + corners @ np.array([[np.cos(a), np.sin(a)], [-np.sin(a), np.cos(a)]])
           for (k, _, _), a in zip(keys, rots)]
    origin = np.min(np.vstack(pts), axis=0)                # every key corner at x, y >= 0
    rows = []
    for p, (k, n, half) in enumerate(keys):
        c = (k['xy'] - origin) / UNIT * 100
        vals = [w, h, c[0] - w / 2, c[1] - h / 2, -k['rot'] * 100, c[0], c[1]]
        rows.append([cu(v) for v in vals] + [f'{p:2d} {half} {n}'])
    widths = [max(len(r[i]) for r in rows) for i in range(7)]
    head = ' ' * len('keys  = <&key_physical_attrs') + ''.join(
        f' {t:>{wd}}' for t, wd in zip(['w', 'h', 'x', 'y', 'rot', 'rx', 'ry'], widths))
    lines = ['//' + head[2:]]
    for i, r in enumerate(rows):
        vals = ''.join(f' {v:>{wd}}' for v, wd in zip(r, widths))
        lines.append(f'{"keys  =" if i == 0 else "      ,"} <&key_physical_attrs{vals}>  // {r[7]}')
    return lines + ['      ;']


def fill(path, body):
    text = path.read_text().split('\n')
    b = next(i for i, l in enumerate(text) if BEGIN in l)
    e = next(i for i in range(b + 1, len(text)) if END in text[i])
    indent = text[b][:len(text[b]) - len(text[b].lstrip())]
    return '\n'.join(text[:b + 1] + [indent + l for l in body] + text[e:])


def main():
    check = '--check' in sys.argv[1:]
    keys = positions()
    assert len(keys) == 36
    want = {SHIELD / 'fortemis.dtsi': layout(keys)}
    for half in ('left', 'right'):
        want[SHIELD / f'fortemis_{half}.overlay'] = gpios(keys, half)
    stale = []
    for path, body in want.items():
        new = fill(path, body)
        if new != path.read_text():
            stale.append(path.relative_to(ROOT))
            if not check:
                path.write_text(new)
    if check and stale:
        sys.exit(f'out of date with the PCBs (run ergogen/tools/zmk.py): {", ".join(map(str, stale))}')
    print(('updated: ' + ', '.join(map(str, stale))) if stale else 'shield matches the PCBs')


if __name__ == '__main__':
    main()
